import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<Heading>
					Welcome to <a href="https://nextjs.org">Next.js!</a>
				</Heading>
			</main>

		</div>
	);
};

const Heading = styled.h1`
	font-size: 5rem;
`;

export default Home;
